/**
 * Identifier Utilities
 * Helper functions for detecting and validating user IDs vs session IDs
 */

/**
 * UUID v4 regex pattern
 * Matches standard UUID format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
 * where x is any hex digit and y is one of 8, 9, a, or b
 */
const UUID_V4_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Relaxed UUID regex pattern (any version)
 * Matches any UUID format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 */
const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Determine if an identifier is a user ID (UUID) or session ID
 * User IDs are UUIDs generated by the database
 * Session IDs are generated by crypto.randomUUID() or nanoid
 *
 * @param identifier - The identifier string to check
 * @returns true if identifier is a UUID (user ID), false if session ID
 *
 * @example
 * isUserId('550e8400-e29b-41d4-a716-446655440000') // true
 * isUserId('abc123xyz') // false
 */
export function isUserId(identifier: string): boolean {
  if (!identifier || typeof identifier !== "string") {
    return false;
  }

  // Check if it matches UUID format (any version)
  return UUID_REGEX.test(identifier);
}

/**
 * Validate identifier format
 * Ensures the identifier is either a valid UUID or a valid session ID
 *
 * @param identifier - The identifier string to validate
 * @returns true if identifier is valid, false otherwise
 *
 * @example
 * isValidIdentifier('550e8400-e29b-41d4-a716-446655440000') // true
 * isValidIdentifier('abc123xyz') // true
 * isValidIdentifier('') // false
 * isValidIdentifier(null) // false
 */
export function isValidIdentifier(identifier: string): boolean {
  if (!identifier || typeof identifier !== "string") {
    return false;
  }

  // Must be non-empty and trimmed
  const trimmed = identifier.trim();
  if (trimmed.length === 0) {
    return false;
  }

  // Either a UUID or a non-empty string (session ID)
  // Session IDs should be at least 8 characters for security
  if (UUID_REGEX.test(trimmed)) {
    return true;
  }

  // For non-UUID identifiers (session IDs), ensure minimum length
  return trimmed.length >= 8;
}

/**
 * Get identifier type as a string
 * Useful for logging and debugging
 *
 * @param identifier - The identifier string to check
 * @returns 'user' if UUID, 'session' if session ID, 'invalid' if neither
 *
 * @example
 * getIdentifierType('550e8400-e29b-41d4-a716-446655440000') // 'user'
 * getIdentifierType('abc123xyz789') // 'session'
 * getIdentifierType('') // 'invalid'
 */
export function getIdentifierType(
  identifier: string
): "user" | "session" | "invalid" {
  if (!isValidIdentifier(identifier)) {
    return "invalid";
  }

  return isUserId(identifier) ? "user" : "session";
}
